Document: osvr-rendermanager
Title: Debian osvr-rendermanager Manual
Author: <insert document author here>
Abstract: This manual describes what osvr-rendermanager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/osvr-rendermanager/osvr-rendermanager.sgml.gz

Format: postscript
Files: /usr/share/doc/osvr-rendermanager/osvr-rendermanager.ps.gz

Format: text
Files: /usr/share/doc/osvr-rendermanager/osvr-rendermanager.text.gz

Format: HTML
Index: /usr/share/doc/osvr-rendermanager/html/index.html
Files: /usr/share/doc/osvr-rendermanager/html/*.html
